# 等差數列之和

## 1.數列之和函數為：summation

summation(一般項 a_i, (i, 初值, 終值)) 。

等差  
$\sum_{i=1}^{10} i$

等比  
$\sum_{i=1}^{10} i*2$  

指數  
$\sum_{i=1}^{10} i^2$  

In [17]:
import sympy as sp    
i=sp.Symbol('i')   
sp.summation(i, (i, 1, 10))    

In [15]:
import sympy as sp    
i=sp.Symbol('i')   
sp.summation(i*2, (i, 1, 10))    

In [19]:
sp.summation(i**2, (i, 1, 10))

## 2.嘗試從 1 到 11 的等差和。

In [59]:
1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10+11

66

In [1]:
import sympy as sp
import numpy as np
n,i= sp.symbols('n,i')
expre= n*5
expr_func= sp.lambdify(n,expre)
a=expr_func(np.arange(12))
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

### 2.1 定義等差d

In [3]:
d=a[2]-a[1]
d

5

### 2.2 通項 a[i], i [1,2,3...n]

註明:電腦從計 a[0] 計算,這里a[0]不使用

In [4]:

(a[1]+(n-1)*d).subs(n,11)

55

### 2.3 數列和

In [67]:
sp.summation(expre, (n, 1, 11)) 

396

### 2.4 計算公式  $\frac{n(n+1)}{2}$  由  n=10  也可要求。

In [13]:
import sympy as sp
n= sp.Symbol('n')

In [16]:
(n*(n + 1)/2)

n*(n + 1)/2

In [58]:
(n*(n + 1)/2).subs(n,11)

66

## 題型一

In [66]:
import sympy as sp
import numpy as np
import random
n= sp.symbols('n')
a1=random.sample(range(-9,10), k=10)
print(a1)
for i in range(10):
    a2=random.randrange(10) +1 
    a3=(a2+random.choice(range(4,7)) )% 11 ;a3=a3 if a3>0 else 1;
    d=a1[i]; d= d if d!=0 else 1
    expre= n*d
    expr_func= sp.lambdify(n,expre)
    a=expr_func(np.arange(12))
    print(a)
    St=f"己知 a{a2}={a[a2]},d={d},求a{a3}?"
    Val=a[a3]
    print(St)
    print(Val)

[4, 0, -8, -1, 8, -3, -5, 3, 2, 6]
[ 0  4  8 12 16 20 24 28 32 36 40 44]
己知 a10=40,d=4,求a3?
12
[ 0  1  2  3  4  5  6  7  8  9 10 11]
己知 a9=9,d=1,求a2?
2
[  0  -8 -16 -24 -32 -40 -48 -56 -64 -72 -80 -88]
己知 a1=-8,d=-8,求a6?
-48
[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11]
己知 a3=-3,d=-1,求a8?
-8
[ 0  8 16 24 32 40 48 56 64 72 80 88]
己知 a3=24,d=8,求a8?
64
[  0  -3  -6  -9 -12 -15 -18 -21 -24 -27 -30 -33]
己知 a10=-30,d=-3,求a5?
-15
[  0  -5 -10 -15 -20 -25 -30 -35 -40 -45 -50 -55]
己知 a2=-10,d=-5,求a8?
-40
[ 0  3  6  9 12 15 18 21 24 27 30 33]
己知 a1=3,d=3,求a7?
21
[ 0  2  4  6  8 10 12 14 16 18 20 22]
己知 a3=6,d=2,求a8?
16
[ 0  6 12 18 24 30 36 42 48 54 60 66]
己知 a8=48,d=6,求a1?
6


## 題型二

In [70]:
import sympy as sp
import numpy as np
import random
n= sp.symbols('n')
a1=random.sample(range(-9,10), k=10)
print(a1)
for i in range(10):
    a2=random.randrange(10) +1 
    a3=(a2+random.choice(range(4,7)) )% 11 ;a3=a3 if a3>0 else 1;
    d=a1[i]; d= d if d!=0 else 1
    expre= n*d
    expr_func= sp.lambdify(n,expre)
    a=expr_func(np.arange(21))
    print(a)
    St=f"己知 a{a2}={a[a2]},a{a3}={a[a3]},求?d"
    Val=d
    print(St)
    print(Val)

[3, -8, 1, -1, 9, -7, 8, 2, 5, -6]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60]
己知 a10=30,a5=15,求?d
3
[   0   -8  -16  -24  -32  -40  -48  -56  -64  -72  -80  -88  -96 -104
 -112 -120 -128 -136 -144 -152 -160]
己知 a7=-56,a1=-8,求?d
-8
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
己知 a5=5,a9=9,求?d
1
[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15 -16 -17
 -18 -19 -20]
己知 a6=-6,a1=-1,求?d
-1
[  0   9  18  27  36  45  54  63  72  81  90  99 108 117 126 135 144 153
 162 171 180]
己知 a3=27,a9=81,求?d
9
[   0   -7  -14  -21  -28  -35  -42  -49  -56  -63  -70  -77  -84  -91
  -98 -105 -112 -119 -126 -133 -140]
己知 a9=-63,a2=-14,求?d
-7
[  0   8  16  24  32  40  48  56  64  72  80  88  96 104 112 120 128 136
 144 152 160]
己知 a10=80,a3=24,求?d
8
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
己知 a10=20,a5=10,求?d
2
[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]
己知 a6=30,a1=5,求?d
5
[   0   -6 

## 題型三

In [88]:
import sympy as sp
import numpy as np
import random
n= sp.symbols('n')
a1=random.sample(range(-9,10), k=10)
print(a1)
for i in range(10):
    a2=random.randrange(6) + 6 
    a3=(a2+random.choice(range(4,7)) )% 11 ;a3=a3 if a3>0 else 1;
    d=a1[i]; d= d if d!=0 else 1
    expre= n*d
    expr_func= sp.lambdify(n,expre)
    a=expr_func(np.arange(18))
    print(a)
    tem_=""
    for i,a_ in enumerate(a):
        if i>0 and i<4  :
            tem_ = tem_+str(a_ )+","
    St=r'己知 {}..{}, S{} ?'.format(tem_,a[a2],a2)
    Val=sp.summation(expre, (n, 1, a2))
    print(St)
    print(Val)

[-5, 7, 3, -7, 2, -2, 9, 4, 6, -8]
[  0  -5 -10 -15 -20 -25 -30 -35 -40 -45 -50 -55 -60 -65 -70 -75 -80 -85]
己知 -5,-10,-15,..-35, S7 ?
-140
[  0   7  14  21  28  35  42  49  56  63  70  77  84  91  98 105 112 119]
己知 7,14,21,..56, S8 ?
252
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51]
己知 3,6,9,..21, S7 ?
84
[   0   -7  -14  -21  -28  -35  -42  -49  -56  -63  -70  -77  -84  -91
  -98 -105 -112 -119]
己知 -7,-14,-21,..-63, S9 ?
-315
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34]
己知 2,4,6,..12, S6 ?
42
[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30 -32 -34]
己知 -2,-4,-6,..-18, S9 ?
-90
[  0   9  18  27  36  45  54  63  72  81  90  99 108 117 126 135 144 153]
己知 9,18,27,..54, S6 ?
189
[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68]
己知 4,8,12,..24, S6 ?
84
[  0   6  12  18  24  30  36  42  48  54  60  66  72  78  84  90  96 102]
己知 6,12,18,..42, S7 ?
168
[   0   -8  -16  -24  -32  -40  -48  -56  -64  -72  -80  -88  -96 -104
 -112 -120 -128 -136]
己知 

## 題型四

In [91]:
import sympy as sp
import numpy as np
import random
n= sp.symbols('n')
a1=random.sample(range(-9,10), k=10)
print(a1)
for i in range(10):
    a2=random.randrange(6) + 6 
    a3=(a2+random.choice(range(4,7)) )% 11 ;a3=a3 if a3>0 else 1;
    d=a1[i]; d= d if d!=0 else 1
    expre= n*d
    expr_func= sp.lambdify(n,expre)
    a=expr_func(np.arange(18))
    print(a)
    St=r'己知 a1={},d={}, S{} ?'.format(a[1],d,a2)
    Val=sp.summation(expre, (n, 1, a2))
    print(St)
    print(Val)

[4, -8, 0, -9, 1, -5, 8, -4, 6, 5]
[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68]
己知 a1=4,d=4, S8 ?
144
[   0   -8  -16  -24  -32  -40  -48  -56  -64  -72  -80  -88  -96 -104
 -112 -120 -128 -136]
己知 a1=-8,d=-8, S7 ?
-224
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
己知 a1=1,d=1, S11 ?
66
[   0   -9  -18  -27  -36  -45  -54  -63  -72  -81  -90  -99 -108 -117
 -126 -135 -144 -153]
己知 a1=-9,d=-9, S8 ?
-324
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
己知 a1=1,d=1, S9 ?
45
[  0  -5 -10 -15 -20 -25 -30 -35 -40 -45 -50 -55 -60 -65 -70 -75 -80 -85]
己知 a1=-5,d=-5, S10 ?
-275
[  0   8  16  24  32  40  48  56  64  72  80  88  96 104 112 120 128 136]
己知 a1=8,d=8, S11 ?
528
[  0  -4  -8 -12 -16 -20 -24 -28 -32 -36 -40 -44 -48 -52 -56 -60 -64 -68]
己知 a1=-4,d=-4, S6 ?
-84
[  0   6  12  18  24  30  36  42  48  54  60  66  72  78  84  90  96 102]
己知 a1=6,d=6, S6 ?
126
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85]
己知 a1=5,d=5, S9 ?
225


## 3. 等比和

In [1]:
1-2+4-8+ 16 -32 +64- 128+ 256 -512 + 1024 

683

In [78]:
exper =-2**(-1)

-0.5

In [85]:
import sympy as sp
import numpy as np
n,i= sp.symbols('n,i')
expre= (-2) ** (n-1)
expr_func= sp.lambdify(n, expre)
n_arr=np.arange(12)
n_arr[0]=1
a=expr_func(n_arr)
a

array([   1,    1,   -2,    4,   -8,   16,  -32,   64, -128,  256, -512,
       1024], dtype=int32)

### 3.1 等比

In [87]:

q=a[4]/a[3]
q

-2.0

### 3.2 通項

In [88]:

expre.subs(n,11)

1024

In [89]:
a[1] * q**(11-1)

1024.0

### 3.3 數列和

In [97]:
(a[1]*(1-q**n)/(1-q)).subs(n,11) 

683.000000000000

In [95]:
(a[1]-a[11]*q)/(1-q)

683.0

In [94]:
sp.summation( expre, (n, 1, 11))     

683

### 3.4 公式表

![](https://appwk.baidu.com/naapi/doc/view?ih=673&o=jpg_6_0_______&iw=678&ix=0&iy=0&aimw=678&rn=1&doc_id=21ad731a59eef8c75fbfb3d0&pn=1&sign=095cfb97e48b57b1777292b350277067&type=1&app_ver=2.9.8.2&ua=bd_800_800_IncredibleS_2.9.8.2_2.3.7&bid=1&app_ua=IncredibleS&uid=&cuid=&fr=3&Bdi_bear=WIFI&from=3_10000&bduss=&pid=1&screen=800_800&sys_ver=2.3.7)

## 4  指數數列之和

$\sum_{i=1}^{10} 2^i$  

In [6]:
import sympy as sp
sp.init_printing("mathjax")                       #
from sympy import div,pdiv,rem,ZZ,QQ 
from IPython.display import Latex,HTML,Markdown    
from sympy.parsing.sympy_parser import parse_expr #文字字串, 解釋成, Sympy 運算式
i=sp.Symbol('i')
sp.summation(2 ** i  , (i, 1, 10))

### 4.1 N項数列指數和

$\sum_{i=1}^{N}  i^2=N(N+1)(2N+1)/6 $

$\sum_{i=1}^{N} i^2  = \frac{N(N+1)(2N+1)}{6}$ 

In [20]:
N= sp.Symbol('N')
sp.summation(i**2, (i, 1, N))

In [21]:
sp.factor(_)


### 練習. 數列之和

第一項  a1 ，公差  d  等差列的第1項至第2項 n 要求一個術語的總和。  
對於初項為3、公比為2的等比數列，求出到第10項之和。  


$\sum_{i=1}^{N}  b_1 * r^(i−1) $ 


問問你 另外，無限等比數列之和  n→∞  問問你 但是， 0<r<1 。  


（提示）

1. 計算如下。 在句子末尾添加時，不顯示結果。; 



In [22]:
a1 = sp.Symbol('a1')
sp.summation(a1 + ( i- 1)*d, (i, 1, n));

In [23]:
b1 = sp.Symbol('b1')
sum2 = sp.summation(b1*r**(i - 1), (i, 1, n))

In [24]:
sum2

   ⎛⎧    n       for r = 1⎞
   ⎜⎪                     ⎟
   ⎜⎪     n + 1           ⎟
b₁⋅⎜⎨r - r                ⎟
   ⎜⎪──────────  otherwise⎟
   ⎜⎪  1 - r              ⎟
   ⎝⎩                     ⎠
───────────────────────────
             r             

## 5.計算的階乘

4  計算的階乘。4! =4×3×2×1=24 是。 在 SymPy 中，階乘使用函數。factorial

In [40]:
factorial(4)

factorial2 函數計算每個場地。 5! ! =5×3×1=15  是。

In [41]:
factorial2(5)


練習
（練習）  3,2,1  最大數位由

使用數位 3、2 和 1 的單一動作可以建立的最大整數是什麼？

（提示）

(1+2)×3=9  那一點也不好。 如果你按原樣排列， 321  但是，使用冪可以創建更大的數位。

213  或者說， 312  或者說， 231  或者說， 321  或者...



## 6 數列之積product
$$\prod_{k=1}^{10} k= 10!$$


In [19]:
import sympy as sp
sp.factorial(10)

In [20]:
import sympy as sp
k=sp.symbols('k',integer=True)
sp.product(k, (k, 1, 10) )

### 6.1 例題


$$\prod_{k=2}^{2021} \frac{k^2-1}{K^2}$$

$$ A_1= \frac{2^2-1}{2^2} \cdot \frac{3^2-1}{3^2}  \cdot \frac{4^2-1}{4^2} \cdot \cdot \cdot \frac{2021^2-1}{2021^2}  $$


<details>
    <summary>Click to reveal solution</summary>
```    
$$ A_1= \frac{(2-1)(2+1)}{2^2} \cdot \frac{(3+1)(3-1)}{3^2}  \cdot \cdot \cdot \frac{(2021-1)(2021+1)}{2021^2}  $$    
$$ A_1= \frac{(1)(3)}{2^2} \cdot \frac{(2)(4)}{3^2}  \cdot \cdot \cdot \frac{(2020)(2022)}{2021^2}  $$
$$ A_1= \frac{(1 * 2 * 3 * 4 \cdot \cdot \cdot 2020) \cdot ( 3 * 4 \cdot \cdot \cdot 2020 * 2021*2022)}{(2 * 3 * 4 \cdot \cdot \cdot 2020 * 2021) *(2 * 3 * 4 \cdot \cdot \cdot 2020 * 2021)}  $$
$$ A_1= \frac{ 2022}{2021 *2} = \frac{1011}{2021} $$    
$$ A_1= \frac{ 2022}{2021 *2} = \frac{1011}{2021} $$
```
</details>




In [21]:
# 計算
print(1011/2021)

# 程式一
A1=1 
for i in range(2,2022): 
    A1 *= (i**2-1)/ (i**2)
print(A1)

# 程式二
A2=1 
for i in range(2,2022): 
    A2 *= sp.S(i**2-1) / sp.S(i**2)
print(A2)


0.500247402276101
0.5002474022761008
1011/2021


In [16]:
expre=(k**2-1)/(k**2)
sp.product(expre, (k, 2, 2021) )

## 7. 資料收集,未整理

### sequences  
https://docs.sympy.org/latest/modules/series/sequences.html

### Combinatorial
https://docs.sympy.org/latest/modules/functions/combinatorial.html   


